// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKFiyj9SPPUPkbXQtoBORHRtabGszIdR4',
    appId: '1:125483789967:web:bc99419f4d80d061270afa',
    messagingSenderId: '125483789967',
    projectId: 'fir-1-e6518',
    authDomain: 'fir-1-e6518.firebaseapp.com',
    storageBucket: 'fir-1-e6518.appspot.com',
    measurementId: 'G-97Y8L55MQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMBv55s5RluSgvBz9Au76DCIlwv2IjG4',
    appId: '1:125483789967:android:bad397ae55b537ab270afa',
    messagingSenderId: '125483789967',
    projectId: 'fir-1-e6518',
    storageBucket: 'fir-1-e6518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjmOo1tlslwSk8HzzwtnMtNO18XSDWdP0',
    appId: '1:125483789967:ios:e540fb3d80744e84270afa',
    messagingSenderId: '125483789967',
    projectId: 'fir-1-e6518',
    storageBucket: 'fir-1-e6518.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjmOo1tlslwSk8HzzwtnMtNO18XSDWdP0',
    appId: '1:125483789967:ios:faf98a7dc19ecc23270afa',
    messagingSenderId: '125483789967',
    projectId: 'fir-1-e6518',
    storageBucket: 'fir-1-e6518.appspot.com',
    iosBundleId: 'com.example.firebase1.RunnerTests',
  );
}
